### ISSUE TITLE
Centralized `go.mod` change not considered as global shared change

### ISSUE THREAD

**Issue by lorenzoranucci** [nx-go/nx-go#164]
### Current Behavior

I use a single go.mod setup.
When I change the go.mod (e.g. by upgrading a dependency), no project is considered as affected.
Example:
```
nx show projects --affected
```
returns no result.

### Expected Behavior

```
nx show projects --affected
```
should return all the Go projects.

### Github Repo

https://github.com/lorenzoranucci/backend-monorepo

### Steps to Reproduce

1. `git checkout  upgrade-deps`
2.  `nx show projects --affected --json`

It returns `[]`. I expect `["quote-domain/shared/go-lib/printer","quote-domain/hello-world-api","shared/go-lib/http"]`.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 24.2.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 11.6.2

nx             : 20.8.2
@nx/workspace  : 20.8.2
@nx/devkit     : 20.8.2
typescript     : 5.3.3
---------------------------------------
Registered Plugins:
@nx-go/nx-go
---------------------------------------
Community plugins:
@nx-go/nx-go : 3.3.1
---------------------------------------
Cache Usage: 0.00 B / 46.04 GB
```

### nx.json

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "defaultBase": "main",
  "namedInputs": {
    "default": [
      "{projectRoot}/**/*",
      "sharedGlobals"
    ],
    "production": [
      "default"
    ],
    "sharedGlobals": [
      "{workspaceRoot}/go.mod"
    ]
  },
  "plugins": [
    "@nx-go/nx-go"
  ],
  "targetDefaults": {
    "lint": {
      "executor": "@nx-go/nx-go:lint",
      "options": {
        "linter": "golangci-lint run"
      }
    }
  }
}
```

### Failure Logs

```shell
Not applicable
```

### Go Version

Go 1.25

**Comment by utarwyn** [comment]
Should be fixed by #170 🤞

**Comment by lorenzoranucci** [comment]
@utarwyn thank you for the effort, but unfortunately #170 didn't fix the issue.

You can reproduce the bug with the same repo and branch I wrote in the issue description.

This is the new Nx Report:

```
 NX   Report complete - copy this into the issue template

Node           : 24.2.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 11.6.2
daemon         : Available

nx             : 22.5.1
@nx/workspace  : 22.5.1
@nx/devkit     : 22.6.0
---------------------------------------
Registered Plugins:
@nx-go/nx-go
---------------------------------------
Community plugins:
@nx-go/nx-go : 4.0.0-beta.0
---------------------------------------
Cache Usage: 0.00 B / 46.04 GB
---------------------------------------
The following packages should match the installed version of nx
  - @nx/devkit@22.6.0

To fix this, run `nx migrate nx@22.6.0`
```

**Comment by utarwyn** [comment]
Thank you for the feedback! I will check that 💪

**Comment by utarwyn** [comment]
Hey @lorenzoranucci 👋 

I have done few tests with your repository, and I can confirm that I reproduce the bug as it is. But I am wondering if you have correctly ran plugin migrations of the version `4.0.0-beta.0`. I have managed to apply them in https://github.com/lorenzoranucci/backend-monorepo/pull/2.

After this little cleanup, the bug does not appear. Can you recheck again starting from the PR I proposed on your repository?
Thank you!

```
▶ nano go.mod
*replace dependency version*

▶ npx nx show projects --affected
quote-domain/shared/go-lib/printer
quote-domain/hello-world-api
shared/go-lib/http
```

**Comment by utarwyn** [comment]
Please answer or re-open the ticket if the problem persists with my PR 🙏
